//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Appointment
{
    public int Id { get; set; }
    public System.DateTime AppointmentDate { get; set; }
    public System.TimeSpan BeginTime { get; set; }
    public System.TimeSpan EndTime { get; set; }
    public int IdService { get; set; }
    public int IdStylist { get; set; }
    public int IdCustomer { get; set; }
    public System.DateTime RegistratrionDate { get; set; }
    public int RegisteredBy { get; set; }

    public virtual Mesxicanito Customer { get; set; }
    public virtual Service Service { get; set; }
    public virtual Stylist Stylist { get; set; }
}

public partial class Mesxicanito
{
    public Mesxicanito()
    {
        this.Appointments = new HashSet<Appointment>();
    }

    public int Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Phone { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; }
}

public partial class Service
{
    public Service()
    {
        this.Appointments = new HashSet<Appointment>();
    }

    public int Id { get; set; }
    public string Service1 { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; }
}

public partial class Stylist
{
    public Stylist()
    {
        this.Appointments = new HashSet<Appointment>();
    }

    public int Id { get; set; }
    public string Stylist1 { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class sp_helpdiagramdefinition_Result
{
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class sp_helpdiagrams_Result
{
    public string Database { get; set; }
    public string Name { get; set; }
    public int ID { get; set; }
    public string Owner { get; set; }
    public int OwnerID { get; set; }
}
